### ISSUE TITLE
Add 7-ways-mobile-data-is-being-used-to-change-the-world post

### ISSUE THREAD

**Issue by tbatun** [UNDataForum/website#15]
Blog post is missing author.

**Comment by 454de6e** [comment]
Blog post was cross-posted here: https://www.oneyoungworld.com/blog/ways-mobile-data-being-used-change-world. @gonzalezmorales: Is there reason why there was no author?

**Comment by 454de6e** [comment]
I will migrate this one and add SDG logos via MDX.

**Comment by 454de6e** [comment]
Blog post Markdown file contained CRLF instead of LF.
