### ISSUE TITLE
Navigation overlaps with promo component

### ISSUE THREAD

**Issue by 454de6e** [UNDataForum/website#231]
![image](https://user-images.githubusercontent.com/57271377/70156067-57ed8e80-1681-11ea-8a91-e6e37036e4b2.png)

cc @faryal06

**Comment by gonzalezmorales** [comment]
I suggest to address this as part of a broader architectural issue about the main navigation and and the main navigation components.  I would like to re-engineer the layout of the home page.  

***[Click here](
https://www.ruckusmarketing.com/?utm_source=10BestDesigns&utm_medium=Directory&utm_term=10BestDesigns&utm_content=10BestDesigns&utm_campaign=10BestDesigns)*** for an example of possible banner styling

![image](https://user-images.githubusercontent.com/7047819/70341944-0cbeb180-1822-11ea-9a39-393d9afd3405.png)

**Comment by gonzalezmorales** [comment]
Please use dark gradient overlay similar to this:
![image](https://user-images.githubusercontent.com/7047819/71266287-19f59900-2316-11ea-96ab-92ff8a9d850b.png)

I think something like this may work:
'background: linear-gradient(#fff 60%, #444);'
https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient

**Comment by 454de6e** [comment]
That's the easy part. But the colors need to come from the theme.

**Comment by 454de6e** [comment]
Prototype: https://github.com/UNDataForum/gatsby-themes/issues/274

**Comment by 454de6e** [comment]
Obsolete with https://github.com/UNDataForum/website/pull/280.
