### ISSUE TITLE
Change last line of the text in About page

### ISSUE THREAD

**Issue by faryal06** [UNDataForum/website#233]
Please change the last line in the About page from "The third United Nations World Data Forum will be hosted by the Federal Statistical Office of Switzerland from 18 to 21 October 2020 in Bern, Switzerland" to "The third United Nations World Data Forum will be hosted by the Swiss Confederation, with substantive support from the Federal Statistical Office from 18 to 21 October 2020 in Bern, Switzerland"

**Comment by 454de6e** [comment]
@gonzalezmorales This was already implemented and reviewed in https://github.com/UNDataForum/website/pull/228.

**Comment by gonzalezmorales** [comment]
👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
