### ISSUE TITLE
Migrate blog post (statisticians-embrace-un-world-data-forum-as-vital-to-innovation)

### ISSUE THREAD

**Issue by tbatun** [UNDataForum/website#266]

**Comment by gonzalezmorales** [comment]
Author missing

**Comment by tbatun** [comment]
Original post does not list author. [link](https://unstats.un.org/unsd/undataforum/statisticians-embrace-un-world-data-forum-as-vital-to-innovation/)


> Author missing

**Comment by gonzalezmorales** [comment]
Published
